### ISSUE TITLE
How to publish the maven plugin to the maven local repository

### ISSUE THREAD

**Issue by gnodet** [tisonkun/os-detector#10]
I haven't used gradle much, and I can't figure out how to publish the built artifacts to the maven local repository so that I can test the plugin in other builds.  Using `./gradlew publishToMavenLocal` fails during the signing phase.
I've tried to disable signing or to configure it... but I can't find a way...

**Comment by tisonkun** [comment]
> fails during the signing phase

Opt out this phase should be fine. You can first delete the related code and we may find a more proper way to switch the condition:

https://github.com/tisonkun/os-detector/blob/3b9a308ecc7cf940bd92440485fb4fa9c0f1d5fc/buildSrc/src/main/kotlin/java-publish.gradle.kts#L70-L74

https://github.com/tisonkun/os-detector/blob/3b9a308ecc7cf940bd92440485fb4fa9c0f1d5fc/plugin-gradle/build.gradle.kts#L80-L84

**Comment by gnodet** [comment]
Thx, I also had to remove the references to the `signing` plugin, but it worked !

**Comment by gnodet** [comment]
Fwiw, I also tried to define an env variable `GITHUB_WORKFLOW = CI`, but that did not work.
